spring.application.name=oncare_backend

# [1] 내장 톰캣의 포트 번호 변경 가능 (기본값 = 8080)
server.port = 8080

# 2-1: 연동할 DB 주소 (DB 메타데이터, 미리 만들어진)
spring.datasource.url=jdbc:mysql://localhost:3306/oncare

# 2-2: DB 주소의 계정명/비밀번호
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# [3] 초기화 모드 강제 활성화
spring.sql.init.mode=always

# 2. 샘플 파일 - 경로 앞 슬래시 제거 (src/main/resources/sql/*.sql 위치)
spring.sql.init.data-locations=classpath:sql/oncare.sql


# 3. Hibernate 테이블 생성 후 스크립트 실행
spring.jpa.defer-datasource-initialization=true

# DDL
spring.jpa.hibernate.ddl-auto=create

# 에러 로그
spring.sql.init.continue-on-error=false

# 한글 인코딩
spring.sql.init.encoding=UTF-8